Repository Lambda-School-Labs/nutrivurv-be, pull requests merged in 2020-06, with the labels that each got.

#50 Code Climate CI/Badge-Link Fix
  .github/workflows/nodejs.yml
  .gitignore
  README.md
  coverage/coverage-summary.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/favicon.png
  coverage/lcov-report/formatDate.js.html
  coverage/lcov-report/generateToken.js.html
  coverage/lcov-report/getUserId.js.html
  coverage/lcov-report/hashPassword.js.html
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov-report/thirdPartyAuth.js.html
  coverage/lcov-report/validateLogin.js.html
  coverage/lcov.info
Labels: bug, documentation

#51 Remove Auth0
  resolvers/mutations/User.js
  utils/thirdPartyAuth.js
Labels: enhancement

#54 Code Climate Config: Similar Code Checks & Line # Threshold
  .codeclimate.yml
Labels: Code Smell

#53 refactor/47-utils
  .gitignore
  server.js
  tests/Utilities.spec.js
  utils/authorization.js
  utils/generateToken.js
  utils/getUserId.js
  utils/hashPassword.js
Labels: Code Smell

#56 Feature/users
  README.md
  api/controllers/index.js
  api/controllers/users.js
  api/routes/auth.js
  api/routes/index.js
  api/server.js
  db/config.js
  db/migrations/20200616193923_create_users_table.js
  db/seeds/development/00-cleanup.js
  db/seeds/development/01-users.js
  index.js
  knexfile.js
  package-lock.json
  package.json
  tests/Utilities.spec.js
  tests/server.spec.js
Labels: enhancement
